### ISSUE TITLE
v1.1 Doesn't work on Mojave ☹️

### ISSUE THREAD

**Issue by minimum91** [jwhamilton99/menu-bar-splitter#1]
<img width="450" alt="Screenshot 2020-04-30 at 20 42 15" src="https://user-images.githubusercontent.com/761247/80741883-17f0e180-8b23-11ea-9fa1-fa10dbb7401e.png">

**Comment by jwhamilton99** [comment]
This is intentional. MBS requires macOS Catalina or later.
