### ISSUE TITLE
Not available via Homebrew Cask

### ISSUE THREAD

**Issue by Jon-Schneider** [jwhamilton99/menu-bar-splitter#2]
It would be awesome if this were available via Homebrew cask so that users could script the install.

**Comment by jwhamilton99** [comment]
I wouldn't even know how to go about making MBS available via Homebrew. I also prefer direct downloads, so I won't do this unless there's significant demand for it.

**Comment by jaklan** [comment]
@jwhamilton99 it's actually quite simple and there are many examples in the repo:
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

From my perspective it would be really beneficial, because now it's the only app I have to install manually 😉

**Comment by jaklan** [comment]
@jwhamilton99 I've already created a cask, the pull request is here:
https://github.com/Homebrew/homebrew-cask/pull/105633

**Comment by jwhamilton99** [comment]
Oh wow, that's so nice of you! Looks like the cask is working properly, so I'll just update the readme with that as well. Thank you!!
