### ISSUE TITLE
Scrambles Menu Bar Icon Order on Every Restart

### ISSUE THREAD

**Issue by jacobjivanov** [jwhamilton99/menu-bar-splitter#3]
Every time my Macbook Air, Mac OS 11.0.1 restarts, or Menu Bar Splitter is restarted, the order of my Menu Bar gets scrambled. Not really a big deal, but very annoying.

**Comment by jwhamilton99** [comment]
This seems to be an issue with macOS' menu bar system in general. I'll see if I can improve this.

**Comment by jwhamilton99** [comment]
With the next version, splitters will use a unique UUID which is preserved between restarts. This makes sure splitters will show up in the correct positions every restart.
