### ISSUE TITLE
Feature Request: Add thinner line icon

### ISSUE THREAD

**Issue by thomasbachem** [jwhamilton99/menu-bar-splitter#5]
Would be great to have a thinner line separator icon.

**Comment by jwhamilton99** [comment]
macOS Big Sur dramatically increased the size of menu bar icons. This might not be the app, but macOS itself. However, I'm considering adding an icon width adjustment in the next version, so that should remedy this.

**Comment by KaKi87** [comment]
Hi,

Basically it would be nice if the app would allow customizing the zoom level of the icon.

What I ended up doing is creating a divider myself from an icon pack and giving it a lot of vertical padding, i.e. increasing the canvas height without increasing the image height.

Here's the resulting file :

| ![](https://github.com/user-attachments/assets/c1861baf-d3de-4a9a-9bde-2337ecf6326d)
| ---

And how it looks like in Pinta :

![](https://github.com/user-attachments/assets/dbc262a1-44d3-4713-99a9-dbc1afc148d1)

Thanks
