### ISSUE TITLE
Feature Request: Ability to easily add custom icons

### ISSUE THREAD

**Issue by thomasbachem** [jwhamilton99/menu-bar-splitter#6]
Would love to be able to use custom icons. Either by specifying an imageset/PNG in the menu dropdown or just hardcoding a folder to drop them into, e.g. `~/Library/Application Support/MenuBarSplitter/Icons/`.

This would also solve my other feature requests #4 and #5.

**Comment by jwhamilton99** [comment]
This is definitely something I want to add. If I can get it working, this will be in a future update.

**Comment by jwhamilton99** [comment]
I have built a system to add and remove custom icons, and will be included in the next update.
