### ISSUE TITLE
How to upload Apple Silicon version

### ISSUE THREAD

**Issue by kalafalas** [jwhamilton99/menu-bar-splitter#7]
Hello! I love this little app and have used it for a while now. I recently got an M1 Mac, and noticed this app runs in rosetta emulation.

I don't have any experience with coding, so forgive me for being a bit lost here. But I was able to successfully download the Xcode project, and export it as a .app and it automatically made it a universal binary, and runs with no problems at all - but now nice and native :)

Any way I can help upload a new version that includes this native M1 support? thank you so much!

**Comment by jwhamilton99** [comment]
I've been super busy with personal engagements, so I haven't been able to work on MBS for a while. I'll update the binary with ASi support in the next week or so!
