### ISSUE TITLE
Splitters Wont Delete

### ISSUE THREAD

**Issue by anonymousaga** [jwhamilton99/menu-bar-splitter#8]
First of all, I use this app to organize my menu bar and love it! I tried Vanilla for menu bar, but this solution, in my opinion, worked better. However, in the latest 2.0 version, I have been having an issue.

Whenever I delete a splitter, shut down my mac, and start it back up, the splitter reappears on the very left. I upgraded from version 1.1 to version 2.0 before this occurred, so I believe this is an issue with your latest release.

**Comment by anonymousaga** [comment]
I'm following up on this issue in case you missed it.

**Comment by jwhamilton99** [comment]
damn guess i missed this. i'll work on it

**Comment by anonymousaga** [comment]
thanks once again for your effort on this app. It has really helped me.

**Comment by jwhamilton99** [comment]
i've fixed this issue, and it will be included in the next update. thanks for your feedback!

**Comment by anonymousaga** [comment]
Will the next update be released in a few days?

**Comment by jwhamilton99** [comment]
yea i’ll try to release it in the next week, probably sooner if i don’t find any other issues

**Comment by anonymousaga** [comment]
Thanks
